name: Process Data

on:
  push:
    branches: [main, master]
    paths: ['data/vocabs/**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process:
    uses: Kurrawong/prez-lite/.github/workflows/site-process-data.yml@main
    with:
      prez-lite-ref: ${{ vars.PREZ_LITE_VERSION || 'main' }}
    secrets:
      prez-lite-token: ${{ secrets.PREZ_LITE_TOKEN }}
